version: '3.0'

services:
    monitorapa:
        container_name: monitorapa
        image: monitorapa
        build:
            context: .
            dockerfile: ./Dockerfile

        volumes:
            - .:/usr/src/app/monitorapa
            #- ./cli:/usr/src/app/monitorapa/cli
            #- ./check:/usr/src/app/monitorapa/check
        restart: unless-stopped
        stdin_open: true
        tty: true
